CREATE TABLE Options_Historical_Data_Master (
    Options_Historical_Data_ID INT IDENTITY(1,1) PRIMARY KEY,
    ContractID NVARCHAR(255) NOT NULL,
    Symbol NVARCHAR(255) NOT NULL,
    Expiration DATE NOT NULL,
    Strike FLOAT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Last FLOAT,
    Mark FLOAT,
    Bid FLOAT,
    Bid_Size INT,
    Ask FLOAT,
    Ask_Size INT,
    Volume INT NOT NULL,
    Open_Interest INT,
    Date DATE NOT NULL,
    Implied_Volatility FLOAT NOT NULL,
    Delta FLOAT,
    Gamma FLOAT,
    Theta FLOAT,
    Vega FLOAT,
    Rho FLOAT,
    Created_On DATETIME NOT NULL DEFAULT GETDATE()
);
