CREATE TABLE Alpha_Vantage_API_Keys (
	API_KEY_ID INT IDENTITY(1,1) PRIMARY KEY,
	API_Key VARCHAR(20) NOT NULL,
	Email VARCHAR(255) NULL,
	Created_on DATETIME NOT NULL DEFAULT GETDATE(),
	Updated_on DATETIME NOT NULL DEFAULT GETDATE(),
	UNIQUE (API_Key),
	UNIQUE (Email)
);