CREATE TABLE Alpha_Vantage_API_Key_Usage (
	Usage_ID INT IDENTITY(1,1) PRIMARY KEY,
	API_Key_ID INT NOT NULL,
	API_KEY VARCHAR(20) NOT NULL,
	Used_At_HK_Time DATETIME NOT NULL DEFAULT GETDATE(),
	Used_At_US_Time DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Eastern Standard Time'),
	Created_On DATETIME NOT NULL DEFAULT GETDATE(),
	Updated_On DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (API_Key_ID) REFERENCES Alpha_Vantage_API_Keys(API_KEY_ID),
	FOREIGN KEY (API_KEY) REFERENCES Alpha_Vantage_API_Keys(API_KEY)
);
