CREATE TABLE Options_Historical_Data_Master (
    Options_Historical_Data_ID INT IDENTITY(1,1) PRIMARY KEY,
    ContractID NVARCHAR(255),
    Symbol NVARCHAR(255),
    Expiration DATE,
    Strike FLOAT,
    Type NVARCHAR(50),
    Last FLOAT,
    Mark FLOAT,
    Bid FLOAT,
    Bid_Size INT,
    Ask FLOAT,
    Ask_Size INT,
    Volume INT,
    Open_Interest INT,
    Date DATE,
    Implied_Volatility FLOAT,
    Delta FLOAT,
    Gamma FLOAT,
    Theta FLOAT,
    Vega FLOAT,
    Rho FLOAT,
    Created_On DATETIME NOT NULL DEFAULT GETDATE()
);